Repository Bit-Baratie/YumYumBack, pull requests merged in 2024-06, with the labels that each got.

#1 feat/엔티티 컬럼 DB와 매핑
  src/main/java/org/baratie/yumyum/domain/category/domain/Category.java
  src/main/java/org/baratie/yumyum/domain/favorite/domain/Favorite.java
  src/main/java/org/baratie/yumyum/domain/hashtag/domain/Hashtag.java
  src/main/java/org/baratie/yumyum/domain/image/domain/Image.java
  src/main/java/org/baratie/yumyum/domain/image/domain/ImageType.java
  src/main/java/org/baratie/yumyum/domain/likes/domain/Likes.java
  src/main/java/org/baratie/yumyum/domain/member/domain/Member.java
  src/main/java/org/baratie/yumyum/domain/member/domain/Role.java
  src/main/java/org/baratie/yumyum/domain/menu/domain/Menu.java
  src/main/java/org/baratie/yumyum/domain/review/domain/Review.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
Labels: enhancement

#2 feat/BaseTimeEntity 설정
  src/main/java/org/baratie/yumyum/domain/BaseTimeEntity.java
  src/main/java/org/baratie/yumyum/domain/image/domain/Image.java
  src/main/java/org/baratie/yumyum/domain/member/domain/Member.java
  src/main/java/org/baratie/yumyum/domain/review/domain/Review.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
Labels: enhancement

#3 feat : 누락된 컬럼 추가
  src/main/java/org/baratie/yumyum/domain/favorite/domain/Favorite.java
  src/main/java/org/baratie/yumyum/domain/hashtag/domain/Hashtag.java
  src/main/java/org/baratie/yumyum/domain/image/domain/Image.java
  src/main/java/org/baratie/yumyum/domain/member/domain/Member.java
  src/main/java/org/baratie/yumyum/domain/member/domain/SocialType.java
  src/main/java/org/baratie/yumyum/domain/reply/domain/Reply.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
Labels: feat

#4 feat : 누락된 컬럼 추가
  src/main/java/org/baratie/yumyum/domain/review/domain/Review.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
Labels: feat

#6 feat : 시큐리티, jwt 코드 작성
  build.gradle
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/LoginDTO.java
  src/main/java/org/baratie/yumyum/domain/member/dto/MemberDTO.java
  src/main/java/org/baratie/yumyum/domain/member/repository/MemberRepository.java
  src/main/java/org/baratie/yumyum/domain/member/service/JwtService.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberDetails.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
  src/main/java/org/baratie/yumyum/global/exception/AuthEntryPoint.java
  src/main/java/org/baratie/yumyum/global/exception/JwtAccessDeniedHandler.java
Labels: feat

#8 feat : 내 정보 보기 기능 구현
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/MemberDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
Labels: feat

#9 feat : 맛집 상세 정보 보기 기능 구현
  src/main/java/org/baratie/yumyum/domain/favorite/repository/FavoriteRepository.java
  src/main/java/org/baratie/yumyum/domain/hashtag/domain/Hashtag.java
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/HashtagRepository.java
  src/main/java/org/baratie/yumyum/domain/menu/domain/Menu.java
  src/main/java/org/baratie/yumyum/domain/menu/repository/MenuRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewRepository.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreRepository.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat

#11 fix : 맛집 상세 Dto 수정, swagger jwt 적용
  src/main/java/org/baratie/yumyum/domain/hashtag/dto/HashtagDto.java
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/HashtagRepository.java
  src/main/java/org/baratie/yumyum/domain/member/Filter/JwtAuthenticationFilter.java
  src/main/java/org/baratie/yumyum/domain/menu/dto/MenuDto.java
  src/main/java/org/baratie/yumyum/domain/menu/repository/MenuRepository.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreRepository.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
  src/main/java/org/baratie/yumyum/global/config/SwaggerConfig.java
Labels: fix

#12 feat : StoreNotFoundException
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/store/exception/StoreNotFoundException.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/java/org/baratie/yumyum/global/exception/ErrorCode.java
Labels: feat

#14 feat : CustomUserDetails 구현체 생성
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/domain/CustomUserDetails.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberDetails.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
Labels: feat

#15 fix : @AuthenticationPrincipal
  src/main/java/org/baratie/yumyum/domain/favorite/controller/FavoriteController.java
  src/main/java/org/baratie/yumyum/domain/favorite/dto/FavoriteDto.java
  src/main/java/org/baratie/yumyum/domain/favorite/service/FavoriteService.java
  src/main/java/org/baratie/yumyum/domain/member/Filter/JwtAuthenticationFilter.java
  src/main/java/org/baratie/yumyum/domain/member/domain/CustomUserDetails.java
  src/main/java/org/baratie/yumyum/domain/member/service/JwtService.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberDetails.java
Labels: fix
