Repository Bit-Baratie/YumYumBack, pull requests merged in 2024-07, with the labels that each got.

#24 Feat/create review
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/UpdateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat

#25 feat : 리뷰 전체리스트 조회
  src/main/java/org/baratie/yumyum/domain/image/dto/ImageDto.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewAllDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
Labels: feat

#26 feat : 댓글 작성, 수정, 삭제 기능 구현
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/reply/domain/Reply.java
  src/main/java/org/baratie/yumyum/domain/reply/dto/CreateReplyDto.java
  src/main/java/org/baratie/yumyum/domain/reply/dto/UpdateRelyDto.java
  src/main/java/org/baratie/yumyum/domain/reply/exception/ReplyNotFoundException.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/global/exception/ErrorCode.java
Labels: feat

#29 fix : 맛집 등록, 수정 기능 수정
  src/main/java/org/baratie/yumyum/domain/hashtag/domain/Hashtag.java
  src/main/java/org/baratie/yumyum/domain/image/domain/Image.java
  src/main/java/org/baratie/yumyum/domain/member/service/JwtService.java
  src/main/java/org/baratie/yumyum/domain/menu/domain/Menu.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/UpdateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: fix

#30 Feat/top10
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/dto/MainStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: feat

#34 Feat/myreply
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/MyInfoDto.java
  src/main/java/org/baratie/yumyum/domain/member/dto/MyReplyDto.java
  src/main/java/org/baratie/yumyum/domain/member/dto/SignUpDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/ReplyCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/impl/ReplyRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
Labels: feat, refactor

#35 feat : 좋아요한 리뷰 조회 기능 구현
  src/main/java/org/baratie/yumyum/domain/likes/repository/Impl/LikesCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/review/dto/CreateReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
Labels: feat

#37 chore : 메서드 위치 조정
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/service/JwtService.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberDetailsService.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/review/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
Labels: chore

#39 refactor : 존재하는지 and 탈퇴 회원인지 검증만 하는 쿼리로 분리
  src/main/java/org/baratie/yumyum/domain/favorite/controller/FavoriteController.java
  src/main/java/org/baratie/yumyum/domain/member/repository/MemberCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/member/repository/MemberRepository.java
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
Labels: refactor

#40 feat : 내가 작성한 리뷰 조회
  src/main/java/org/baratie/yumyum/domain/likes/controller/LikesController.java
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/review/dto/MyReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
Labels: feat

#41 refactor : 묵시적 조인 명시
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
Labels: refactor

#42 feat : 회원 정보 수정
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/domain/Member.java
  src/main/java/org/baratie/yumyum/domain/member/dto/UpdateMemberDto.java
  src/main/java/org/baratie/yumyum/domain/member/exception/PasswordNotEqualException.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/global/exception/ErrorCode.java
Labels: feat

#43 chore : 맛집 상세 조회 가게 평균 평점 추가
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/HashtagRepository.java
  src/main/java/org/baratie/yumyum/domain/image/repository/ImageRepository.java
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/LoginResponseDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/menu/repository/MenuRepository.java
  src/main/java/org/baratie/yumyum/domain/review/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewAllDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: chore

#44 Feat/adminstore
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewAllDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/dto/AdminStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/MainStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat

#46 feat : 즐겨찾기한 맛집 조회
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/dto/MyFavoriteStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat

#51 feat : 리뷰 상세 페이지 좋아요 상태 반환
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewDetailDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
Labels: feat

#52 Feat/search store
  src/main/java/org/baratie/yumyum/domain/likes/dto/LikesDto.java
  src/main/java/org/baratie/yumyum/domain/likes/service/LikesService.java
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/LoginResponseDto.java
  src/main/java/org/baratie/yumyum/domain/member/dto/SignUpDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/SearchStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat, chore

#53 Feat/nearbystore
  build.gradle
  src/main/java/org/baratie/yumyum/domain/review/dto/CreateReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat, chore

#57 feat : 관리자 페이지 리뷰 신고 조회 및 댓글 신고 조회 기능 구현
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/MyInfoDto.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/ReplyRepository.java
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
  src/main/java/org/baratie/yumyum/domain/report/domain/Report.java
  src/main/java/org/baratie/yumyum/domain/report/domain/ReportType.java
  src/main/java/org/baratie/yumyum/domain/report/dto/ReportPageResponseDto.java
  src/main/java/org/baratie/yumyum/domain/report/repository/Impl/ReportCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/report/repository/ReportCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/report/repository/ReportRepository.java
  src/main/java/org/baratie/yumyum/domain/report/service/ReportService.java
  src/main/java/org/baratie/yumyum/domain/review/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/dto/SearchStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: feat, chore

#58 feat : 가게/리뷰/댓글 신고 기능 구현
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
  src/main/java/org/baratie/yumyum/domain/report/domain/Report.java
  src/main/java/org/baratie/yumyum/domain/report/dto/CreateReportDto.java
  src/main/java/org/baratie/yumyum/domain/report/service/ReportService.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: feat

#61 fix : 네이버 소셜 로그인
  src/main/java/org/baratie/yumyum/domain/member/handler/OAuth2SuccessHandler.java
  src/main/java/org/baratie/yumyum/domain/member/repository/MemberCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/member/service/OAuth2Service.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: fix

#63 chore : 프론트와 연동과정 중 필요한 데이터 값 추가
  src/main/java/org/baratie/yumyum/domain/reply/dto/ReplyResponseDto.java
  src/main/java/org/baratie/yumyum/domain/report/dto/ReportPageResponseDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewAllDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewDetailDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: chore

#66 Feat/image upload
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/SignUpDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/review/dto/CreateReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewAllDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/dto/CreateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/java/org/baratie/yumyum/global/exception/ErrorCode.java
  src/main/java/org/baratie/yumyum/global/utils/file/domain/Image.java
  src/main/java/org/baratie/yumyum/global/utils/file/exception/FileUploadException.java
  src/main/java/org/baratie/yumyum/global/utils/file/repository/ImageRepository.java
  src/main/java/org/baratie/yumyum/global/utils/file/service/ImageService.java
Labels: feat

#69 Chore/file path
  src/main/java/org/baratie/yumyum/domain/member/controller/AuthController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/MyPageController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/Oauth2Controller.java
  src/main/java/org/baratie/yumyum/domain/member/controller/admin/AdminMemberController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/admin/AdminReplyController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/admin/AdminReviewController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/admin/AdminStoreController.java
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
Labels: chore

#71 chore : 서비스 레이어 분리
  src/main/java/org/baratie/yumyum/domain/store/controller/RankingController.java
  src/main/java/org/baratie/yumyum/domain/store/controller/SearchController.java
  src/main/java/org/baratie/yumyum/domain/store/service/RankingService.java
  src/main/java/org/baratie/yumyum/domain/store/service/SearchService.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: chore

#72 Chore/file path
  src/main/java/org/baratie/yumyum/domain/member/Filter/JwtAuthenticationFilter.java
  src/main/java/org/baratie/yumyum/domain/member/controller/AdminController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/AuthController.java
  src/main/java/org/baratie/yumyum/domain/member/handler/OAuth2SuccessHandler.java
  src/main/java/org/baratie/yumyum/domain/member/service/AdminService.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/AuthService.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/JwtService.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/MemberDetailsService.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/OAuth2Service.java
  src/main/java/org/baratie/yumyum/domain/store/controller/SearchController.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
  src/main/java/org/baratie/yumyum/global/config/SwaggerConfig.java
Labels: chore

#73 chore : 리뷰 서비스 레이어 분리
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewReadController.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewReadService.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
Labels: chore

#74 chore : 파일 구조 변경 및 컨트롤러 분리
  src/main/java/org/baratie/yumyum/domain/member/controller/MyPageController.java
  src/main/java/org/baratie/yumyum/domain/member/service/MyPageService.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: chore

#75 chore : 가게 레포지토리 레이어 분리
  src/main/java/org/baratie/yumyum/domain/store/repository/RankingCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/SearchCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/RankingCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: chore

#76 chore : 안 쓰는 코드 삭제
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: chore

#78 feat : 회원가입, 내정보 수정 시 image 등록 기능 구현
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/domain/Member.java
  src/main/java/org/baratie/yumyum/domain/member/dto/UpdateMemberDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/AuthService.java
  src/main/java/org/baratie/yumyum/global/utils/file/service/ImageService.java
Labels: feat

#79 feat : 가게 등록, 수정 시 이미지 등록 기능 구현
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/UpdateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/resources/application.yml
Labels: feat

#80 refactor : 리뷰 상세조회 쿼리 리팩토링
  src/main/java/org/baratie/yumyum/domain/member/dto/MemberBasicDto.java
  src/main/java/org/baratie/yumyum/domain/member/repository/MemberCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewDetailDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewReadService.java
Labels: refactor

#81 feat : 가게 신고 목록 조회 기능 구현
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
  src/main/java/org/baratie/yumyum/domain/report/repository/Impl/ReportCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/report/repository/ReportCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/report/service/ReportService.java
Labels: feat

#82 fix : 관리자페이지 회원 조회 memberId 추가
  src/main/java/org/baratie/yumyum/domain/member/dto/SimpleMemberDto.java
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
Labels: fix

#83 refactor : slice 객체 필요없는 컬럼 빼고 반환
  src/main/java/org/baratie/yumyum/domain/member/controller/MyPageController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/MemberBasicDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MyPageService.java
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewReadController.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewReadService.java
  src/main/java/org/baratie/yumyum/global/utils/pageDto/CustomSliceDto.java
Labels: refactor

#84 Refactor/search store
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewService.java
  src/main/java/org/baratie/yumyum/domain/store/dto/SearchStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/global/utils/file/service/ImageService.java
Labels: fix, refactor

#85 fix : 마이페이지 좋아요한 리뷰, 즐겨찾기한 맛집 이미지 기능 추가
  src/main/java/org/baratie/yumyum/domain/review/dto/MyReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/MyReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/dto/MyFavoriteStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: fix

#86 refactor : 어드민 페이지 멤버조회 파라미터 삭제
  src/main/java/org/baratie/yumyum/domain/member/controller/AdminController.java
  src/main/java/org/baratie/yumyum/domain/member/filter/JwtAuthenticationFilter.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: refactor

#87 fix : 로그인 시 유저 Role 정보 리턴
  src/main/java/org/baratie/yumyum/domain/member/dto/LoginResponseDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/AuthService.java
Labels: fix

#88 fix : 체크 비밀번호 안 받게 변경 and 비밀번호 null 처리
  src/main/java/org/baratie/yumyum/domain/member/dto/UpdateMemberDto.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
Labels: fix

#89 fix : 시큐리티 어드민권한 부여 수정 및 변수명 통일
  src/main/java/org/baratie/yumyum/domain/category/domain/Category.java
  src/main/java/org/baratie/yumyum/domain/category/dto/CategoryDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/LikeReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/MyReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewAllDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/ReviewDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/CreateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/MyFavoriteStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/SearchStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: fix, chore

#90 fix : 시큐리티 어드민권한 부여 수정
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: fix

#91 fix : CustomUserDetails getAuthorities 수정
  src/main/java/org/baratie/yumyum/domain/member/domain/CustomUserDetails.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: fix

#92 fix : 페이지네이션 수정
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/member/service/AdminService.java
  src/main/java/org/baratie/yumyum/domain/report/repository/Impl/ReportCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: fix

#93 myReview : N + 1 문제 해결
  src/main/java/org/baratie/yumyum/domain/member/service/MyPageService.java
  src/main/java/org/baratie/yumyum/domain/review/repository/MyReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/MyReviewCustomRepositoryImpl.java
Labels: refactor

#94 refactor : Jpa N+1 문제 해결을 위해 image, hashtag 분리하여 dto에 담음
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/HashtagCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/HashtagRepository.java
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/Impl/HashtagCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewReadService.java
  src/main/java/org/baratie/yumyum/domain/store/repository/SearchCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/SearchService.java
  src/main/java/org/baratie/yumyum/global/utils/file/repository/ImageCustomRepository.java
  src/main/java/org/baratie/yumyum/global/utils/file/repository/impl/ImageCustomRepositoryImpl.java
Labels: refactor

#95 fix : 맛집 정보 이미지 1개만 담아주는 방식으로 변경
  src/main/java/org/baratie/yumyum/domain/review/repository/ReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/service/ReviewReadService.java
  src/main/java/org/baratie/yumyum/domain/store/dto/SearchStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/SearchCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/SearchService.java
  src/main/java/org/baratie/yumyum/global/utils/file/repository/ImageCustomRepository.java
  src/main/java/org/baratie/yumyum/global/utils/file/repository/impl/ImageCustomRepositoryImpl.java
Labels: fix

#96 myReview : N + 1 문제 해결 및 이미지 한 개만 조회
  src/main/java/org/baratie/yumyum/domain/member/service/MyPageService.java
  src/main/java/org/baratie/yumyum/domain/store/dto/MyFavoriteStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/StoreCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: refactor

#97 chore : 가게 조회시 변수명 imageList -> imageUrl로 변경
  src/main/java/org/baratie/yumyum/domain/store/dto/SearchStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
Labels: chore

#98 likeReview : N + 1 문제 해결
  src/main/java/org/baratie/yumyum/domain/member/service/MyPageService.java
  src/main/java/org/baratie/yumyum/domain/review/repository/MyReviewCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/MyReviewCustomRepositoryImpl.java
Labels: refactor

#99 feat : 관리자페이지 리뷰, 댓글, 가게 삭제
  src/main/java/org/baratie/yumyum/domain/member/controller/AdminController.java
  src/main/java/org/baratie/yumyum/domain/member/service/AdminService.java
  src/main/java/org/baratie/yumyum/domain/reply/domain/Reply.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/ReplyCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/impl/ReplyRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/domain/Review.java
Labels: feat

#100 fix : 소셜 로그인 성공 시 프론트 배포서버 ip로 리다이렉트
  src/main/java/org/baratie/yumyum/domain/member/handler/OAuth2SuccessHandler.java
Labels: fix

#102 refactor : 페이지네이션
  src/main/java/org/baratie/yumyum/domain/member/controller/AdminController.java
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
Labels: refactor

#103 fix : 맛집 리스트 페이지 즐겨찾기 상태 확인 위해 memberId 레파지토리에 전달
  src/main/java/org/baratie/yumyum/domain/store/controller/SearchController.java
  src/main/java/org/baratie/yumyum/domain/store/repository/SearchCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/SearchCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/service/SearchService.java
Labels: fix

#104 refactor : 페이지네이션
  src/main/java/org/baratie/yumyum/domain/member/controller/AdminController.java
  src/main/java/org/baratie/yumyum/domain/member/controller/MyPageController.java
  src/main/java/org/baratie/yumyum/domain/member/service/AdminService.java
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
  src/main/java/org/baratie/yumyum/domain/report/service/ReportService.java
  src/main/java/org/baratie/yumyum/global/utils/pageDto/CustomPageDto.java
  src/main/java/org/baratie/yumyum/global/utils/pageDto/CustomSliceDto.java
Labels: refactor

#105 refactor : validation 추가
  src/main/java/org/baratie/yumyum/domain/favorite/controller/FavoriteController.java
  src/main/java/org/baratie/yumyum/domain/favorite/dto/FavoriteDto.java
  src/main/java/org/baratie/yumyum/domain/likes/controller/LikesController.java
  src/main/java/org/baratie/yumyum/domain/likes/dto/LikesDto.java
  src/main/java/org/baratie/yumyum/domain/member/controller/AuthController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/LoginDto.java
  src/main/java/org/baratie/yumyum/domain/member/dto/SignUpDto.java
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/reply/dto/CreateReplyDto.java
  src/main/java/org/baratie/yumyum/domain/reply/dto/UpdateRelyDto.java
  src/main/java/org/baratie/yumyum/domain/report/controller/ReportController.java
  src/main/java/org/baratie/yumyum/domain/report/dto/CreateReportDto.java
  src/main/java/org/baratie/yumyum/domain/review/controller/ReviewController.java
  src/main/java/org/baratie/yumyum/domain/review/dto/CreateReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/UpdateReviewRequestDto.java
Labels: refactor

#106 fix : 맛집 정보 수정 기능 수정 및 Dto에 @NotBlank 적용
  src/main/java/org/baratie/yumyum/domain/category/dto/CategoryDto.java
  src/main/java/org/baratie/yumyum/domain/hashtag/dto/HashtagDto.java
  src/main/java/org/baratie/yumyum/domain/hashtag/repository/HashtagRepository.java
  src/main/java/org/baratie/yumyum/domain/member/dto/SignUpDto.java
  src/main/java/org/baratie/yumyum/domain/menu/dto/MenuDto.java
  src/main/java/org/baratie/yumyum/domain/store/controller/StoreController.java
  src/main/java/org/baratie/yumyum/domain/store/domain/Store.java
  src/main/java/org/baratie/yumyum/domain/store/dto/CreateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/dto/UpdateStoreDto.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: fix

#107 refactor : 중복 서브쿼리 클래스로 분리
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/global/subquery/TotalAvgGrade.java
  src/main/java/org/baratie/yumyum/global/subquery/TotalReviewCount.java
Labels: refactor

#108 fix : 즐겨찾기 좋아요 어노테이션 수정
  src/main/java/org/baratie/yumyum/domain/favorite/dto/FavoriteDto.java
  src/main/java/org/baratie/yumyum/domain/likes/dto/LikesDto.java
Labels: fix

#109 fix : 어노테이션 수정
  src/main/java/org/baratie/yumyum/domain/favorite/dto/FavoriteDto.java
  src/main/java/org/baratie/yumyum/domain/likes/dto/LikesDto.java
  src/main/java/org/baratie/yumyum/domain/menu/dto/MenuDto.java
  src/main/java/org/baratie/yumyum/domain/reply/dto/CreateReplyDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/CreateReviewDto.java
  src/main/java/org/baratie/yumyum/domain/review/dto/UpdateReviewRequestDto.java
Labels: fix

#111 refactor : 중복 메서드 삭제 후 공통 메서드 적용
  src/main/java/org/baratie/yumyum/domain/favorite/repository/impl/FavoriteRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/likes/repository/Impl/LikesCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/member/repository/impl/MemberCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/impl/ReplyRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/MyReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/RankingCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
Labels: refactor

#112 build : https 적용
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: build

#113 fix : 댓글 삭제 시 replyRepository가 아닌 reviewRepository를 거치는 문제 수정
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
Labels: fix

#114 fix : 맛집 상세 정보 리턴 시 카테고리 컬럼 추가
  src/main/java/org/baratie/yumyum/domain/category/repository/CategoryRepository.java
  src/main/java/org/baratie/yumyum/domain/store/dto/StoreDetailDto.java
  src/main/java/org/baratie/yumyum/domain/store/service/StoreService.java
Labels: fix

#115 build : redis 의존성 추가
  build.gradle
Labels: build

#117 fix : 본인만 댓글 수정, 삭제 할 수 있게 변경
  src/main/java/org/baratie/yumyum/domain/reply/controller/ReplyController.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/ReplyCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/reply/repository/impl/ReplyRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/reply/service/ReplyService.java
  src/main/java/org/baratie/yumyum/global/exception/ErrorCode.java
Labels: fix

#118 fix : 관리자 페이지 삭제된 컬럼 보이는 문제 해결
  src/main/java/org/baratie/yumyum/domain/likes/repository/Impl/LikesCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/likes/repository/LikesCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/likes/repository/LikesRepository.java
  src/main/java/org/baratie/yumyum/domain/member/controller/AdminController.java
  src/main/java/org/baratie/yumyum/domain/member/service/AdminService.java
  src/main/java/org/baratie/yumyum/domain/report/repository/Impl/ReportCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/report/repository/ReportCustomRepository.java
  src/main/java/org/baratie/yumyum/domain/review/domain/Review.java
Labels: fix

#119 feat : 회원 탈퇴
  src/main/java/org/baratie/yumyum/domain/member/controller/MemberController.java
  src/main/java/org/baratie/yumyum/domain/member/service/MemberService.java
Labels: feat

#121 Feat/reissue
  src/main/java/org/baratie/yumyum/domain/member/controller/AuthController.java
  src/main/java/org/baratie/yumyum/domain/member/dto/LoginResponseDto.java
  src/main/java/org/baratie/yumyum/domain/member/dto/TokenDto.java
  src/main/java/org/baratie/yumyum/domain/member/dto/UserDataDto.java
  src/main/java/org/baratie/yumyum/domain/member/filter/JwtAuthenticationFilter.java
  src/main/java/org/baratie/yumyum/domain/member/handler/OAuth2SuccessHandler.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/AuthService.java
  src/main/java/org/baratie/yumyum/domain/member/service/auth/JwtService.java
  src/main/java/org/baratie/yumyum/global/config/SecurityConfig.java
Labels: feat

#122 fix : 즐겨찾기한 맛집 count 에러 해결
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/MyReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/review/repository/impl/ReviewCustomRepositoryImpl.java
  src/main/java/org/baratie/yumyum/domain/store/repository/impl/StoreRepositoryImpl.java
  src/main/java/org/baratie/yumyum/global/subquery/TotalAvgGrade.java
  src/main/java/org/baratie/yumyum/global/subquery/TotalReviewCount.java
Labels: fix
